# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63fb10fc7199ac31bc298eb8eb0e01e776e50bbb4418368cd63cb12c3feff78e0feba4eeb4edf6363812bf17ed5ec332fc6b9aad7be9025cd4fb3b56e7ade3ec

test:
  secret_key_base: 6e1553d0017e62372e8f60d19ca0fb10793cda567cca24ae9f0338f5fc23591fcbd1e5ec9abdd84e49046bb63765ac61968091145afa77cce5ea55fc08e4261b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
